name: 'MrKai. '
favicon: null
layout_spectrum: 0.73888
typography_spectrum: 0.36636
title: "Don't come 'round here no more..."
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0D0E12'
    - '#F1E5CD'
    - '#213D62'
    - '#CF4C52'
    - '#DC837A'
  brandStrength: 0.1875
  lightness: 0.375
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
